name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - if: "!contains(github.event.head_commit.message, '[skip CI]')"
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org
          scope: '@octocat'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:once